server:
  port: 8282
  servlet:
    context-path: /radio-therapie
  tomcat:
    accesslog:
      enabled: false




spring:
  profiles.active: test
  data:
    jpa:
      repositories:
        enabled: true

      show-sql: true
      hibernate:
        ddl-auto: update
  jackson:
    serialization:
        INDENT_OUTPUT: true
        fail-on-empty-beans: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: /opt/tomcat/temp/
  messages:
    encoding: UTF-8
    basename: messages
  jmx:
    enabled: true
  jpa:
   database: postgresql
   show-sql: false
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   
   properties:
    hibernate.ddl-auto: validate
    hibernate.enable_lazy_load_no_trans: true
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.jdbc.lob.non_contextual_creation: true

---
spring:
  profiles: dev
  datasource:
    jndi-name: jdbc/radiotherapie
logging:  
  level:
    root: ERROR
reporting:
  url: http://localhost:8080/REPORTOOLS
  readTimeout: 200000
  connectTimeout: 200000
uploads:
  location: 
    directory: /data/Files/uploads/
    temp: /opt/tomcat8/sih_files/temp/
---


spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/radiotherapie_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "admin"
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
logging:  
  level:
    root: ERROR
reporting:
  url: http://192.168.1.126:9090/REPORTOOLS
  readTimeout: 200000
  connectTimeout: 200000
uploads:
  location: 
    directory: /data/Files/uploads/
    temp: /opt/tomcat8/sih_files/temp/
serverLogs:
 dir: C:/Enova/temp
 filename: radiotherapie
 filextention: .log
 actif: false
---
spring:
  profiles: recette
  datasource:
    jndi-name: jdbc/radiotherapie
logging:  
  level:
    root: ERROR
reporting:
  url: http://localhost:8080/REPORTOOLS
  readTimeout: 200000
  connectTimeout: 200000
uploads:
  location: 
    directory: /data/Files/uploads/
    temp: /opt/tomcat8/sih_files/temp/
---
spring: 
  profiles: prod
  datasource:
    jndi-name: jdbc/radiotherapie 
logging:  
  level:
    root: ERROR
reporting:
  url: http://localhost/REPORTOOLS
  readTimeout: 200000
  connectTimeout: 200000
uploads:
  location: 
    directory: /data/Files/uploads/
    temp: /opt/tomcat8/sih_files/temp/
---
spring: 
  profiles: preprod
  datasource:
    jndi-name: jdbc/radiotherapie    
logging:  
  level:
    root: ERROR
reporting:
  url: http://localhost/REPORTOOLS
  readTimeout: 200000
  connectTimeout: 200000
uploads:
  location: 
    directory: /data/Files/uploads/
    temp: /opt/tomcat8/sih_files/temp/
---
  
# JWT Configuration
jwt:
  header: Authorization
  secret: MY-3N0VA@2017
  expiration: 28800
  bearer-token: true
  authentication:
      authenticate:
          url: auth/authenticate
      token:
          url: auth/token
      logout:
          url: auth/logout          
  
default:
    password: 123456
---
spring:
  http:
    multipart:
      enabled: true
  flyway:
    enabled: true
    encoding: UTF-8
    out-of-order: true
    table: schema_history
    baseline-on-migrate: true

security:
  signing-key: MY-3N0VA@2017
  client-id: enovaClientId
  client-secret: enov@secret
  access-token-validity: 28800
  refresh-token: false   
  refresh-token-validity-seconds: 28800    